name       : font-tt2020-ttf
version    : 0.2.1
release    : 1
source     :
    - https://github.com/ctrlcctrlv/TT2020/archive/refs/tags/v0.2.1.tar.gz : a6c34a7ffce6e2f87c12566724029bde528364ce653805ac3d28a34845d815e7
license    : OFL-1.1-RFN
component  : desktop.font
summary    : TT2020 is an advanced, open source, hyperrealistic, multilingual typewriter font for a new decade.
description: |
    TT2020 is an advanced, open source, hyperrealistic, multilingual typewriter font for a new decade.
install    : |
    install -D -m00644 dist/*.ttf -t $installdir/usr/share/fonts/truetype/TT2020/
